In [ ]:
from claion.pipes.sb_sts import SpeechBrainSTSPipeline
from pathlib import Path
import torch


audio_file_path = Path("../data/speechocean762/train/audios/000000.wav")

pipe = SpeechBrainSTSPipeline(device="cpu", training_mode=True)

pipe.generate_speech(audio_file_path)


Some weights of SpeechT5ForSpeechToSpeech were not initialized from the model checkpoint at microsoft/speecht5_vc and are newly initialized: ['speecht5.encoder.prenet.pos_sinusoidal_embed.weights']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
INFO:speechbrain.utils.fetching:Fetch hyperparams.yaml: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:speechbrain.utils.fetching:Fetch custom.py: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:speechbrain.utils.fetching:Fetch embedding_model.ckpt: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:speechbrain.utils.fetching:Fetch mean_var_norm_emb.ckpt: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:speechbrain.utils.fetching:Fetch classifier.ckpt: Fetching from HuggingFace Hub 'speechbrain/spkrec-xvect-voxceleb' if not cached
INFO:spee

LibsndfileError: Error opening '../data/speechocean762/train/000000.wav': System error.

In [4]:
audio_array, sample_rate = pipe._process_input(audio_file_path)

inputs = pipe.processor(audio=audio_array, sampling_rate=sample_rate, return_tensors="pt").to("cpu")
inputs.input_values.shape, inputs.attention_mask.shape

LibsndfileError: Error opening '../data/speechocean762/train/000000.wav': System error.

In [ ]:

from transformers import SpeechT5ForSpeechToSpeech

model = SpeechT5ForSpeechToSpeech.from_pretrained("microsoft/speecht5_vc")

Some weights of SpeechT5ForSpeechToSpeech were not initialized from the model checkpoint at microsoft/speecht5_vc and are newly initialized: ['speecht5.encoder.prenet.pos_sinusoidal_embed.weights']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.


In [14]:
model.speecht5.encoder.prenet.pos_sinusoidal_embed.weights

Parameter containing:
tensor([[ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
        [ 0.0000,  0.0000,  0.0000,  ...,  0.0000,  0.0000,  0.0000],
        [ 0.9093,  0.9280,  0.9443,  ...,  1.0000,  1.0000,  1.0000],
        ...,
        [-0.9948, -0.7526, -0.9621,  ...,  0.9807,  0.9816,  0.9824],
        [-0.6229, -0.9670, -0.7796,  ...,  0.9806,  0.9816,  0.9824],
        [ 0.3218, -0.3307,  0.0590,  ...,  0.9806,  0.9815,  0.9824]])

In [18]:
import torch

torch.nn.init.normal_(model.speecht5.encoder.prenet.pos_sinusoidal_embed.weights, mean=0.0, std=0.02)

Parameter containing:
tensor([[ 0.0048,  0.0191,  0.0150,  ...,  0.0162, -0.0055,  0.0313],
        [ 0.0108,  0.0101, -0.0289,  ...,  0.0330,  0.0042, -0.0015],
        [ 0.0192, -0.0007,  0.0140,  ..., -0.0435, -0.0118, -0.0241],
        ...,
        [ 0.0156,  0.0086, -0.0080,  ...,  0.0130, -0.0169,  0.0108],
        [ 0.0114,  0.0005, -0.0073,  ...,  0.0081,  0.0053, -0.0139],
        [-0.0084, -0.0231, -0.0080,  ...,  0.0404,  0.0096, -0.0042]])

In [19]:
model.speecht5.encoder.prenet.pos_sinusoidal_embed.weights

Parameter containing:
tensor([[ 0.0048,  0.0191,  0.0150,  ...,  0.0162, -0.0055,  0.0313],
        [ 0.0108,  0.0101, -0.0289,  ...,  0.0330,  0.0042, -0.0015],
        [ 0.0192, -0.0007,  0.0140,  ..., -0.0435, -0.0118, -0.0241],
        ...,
        [ 0.0156,  0.0086, -0.0080,  ...,  0.0130, -0.0169,  0.0108],
        [ 0.0114,  0.0005, -0.0073,  ...,  0.0081,  0.0053, -0.0139],
        [-0.0084, -0.0231, -0.0080,  ...,  0.0404,  0.0096, -0.0042]])